name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted # 使用自托管的 Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Set npm registry
        run: npm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build project
        run: npm run build

      - name: Update site directory
        run: |
          # 使用 GitHub Variables 中定义的路径
          SITE_PATH="${{ vars.SITE_ROOT }}"
          
          # 检查路径是否为空，防止误删根目录
          if [ -z "$SITE_PATH" ]; then
            echo "Error: SITE_ROOT variable is not set."
            exit 1
          fi

          echo "Deploying to $SITE_PATH"
          sudo rm -rf $SITE_PATH/*
          sudo cp -r dist/* $SITE_PATH/
          sudo chown -R www:www $SITE_PATH/